#!/bin/bash
echo 0 > /sys/kernel/debug/tracing/tracing_on
echo 1 > /sys/kernel/debug/tracing/events/syscalls/enable
echo 0 > /sys/kernel/debug/tracing/events/syscalls/sys_enter_clock_nanosleep/en$
echo 0 > /sys/kernel/debug/tracing/events/syscalls/sys_exit_clock_nanosleep/ena$
echo 0 > /sys/kernel/debug/tracing/events/syscalls/sys_enter_wait4/enable
echo 0 > /sys/kernel/debug/tracing/events/syscalls/sys_exit_wait4/enable
echo 4024000 > /sys/kernel/debug/tracing/buffer_size_kb
echo 1 > /sys/kernel/debug/tracing/tracing_on
